---
- hosts: webservers
  remote_user: opc
  become: yes
  become_method: sudo
  tasks:
    - name: Install pip
      yum: name=python-pip state=present
    - name: install docker-engine package
      yum: name=docker-engine state=present
    - name: Make sure a service is running
      systemd:
        state: started
        name: docker
    - name: enable a service docker
      systemd:
        name: docker
        enabled: yes

    - name: running the container
      docker_container:
        name: apex-app
        image: "jshahid21/db-apex-dev-image"
        state: started
        detach: yes
        privileged: yes
        devices: 
          - /dev/shm
        tmpfs: 
          - /dev/shm:rw,nosuid,nodev,exec,size=2g
        published_ports: 2222:22,8080:8080,1521:1521
